package game

// Don't deconflict generated words per game, it could be fun to see different approaches to the same term...
func generateWord() string {
	choice := randomInt(0, len(wordList)-1)
	return wordList[choice]
}

var wordList = []string{
	"Hit the Nail on the Head",
	"Sausage Party",
	"One Child Policy",
	"Road Rage",
	"Lord of the Rings",
	"Licking People's Shoes",
	"Laughing Your Head Off",
	"Death by Salmon",
	"The Never-Ending Poo",
	"Adopting a Cactus",
	"The Blind Leading the Blind",
	"Meat Sweats",
	"Life Giving You Lemons",
	"Freak Show",
	"Scaring Yourself Shitless",
	"1950s Sex Ed Poster",
	"Bangkok Ping Pong Show",
	"Wiping the Smile Off Your Face",
	"Too Much Acid",
	"Armpit Fetish",
	"Joyless Sex",
	"Stealing Someone's Thunder",
	"Lost in IKEA",
	"Badly Drawn-On Eyebrows",
	"Crying on the Inside",
	"Urinating in a Phone Box",
	"Eels, Eels, and More Eels",
	"Brain Freeze",
	"Haunted Oven",
	"Dancing on Someone's Grave",
	"Booty Call",
	"Jazz Hands",
	"Sexually Transmitted Diseases",
	"Naked Sleepwalking",
	"Butt Dialling",
	"Octopus Mating Season",
	"Muffin Top",
	"Sex Bomb",
	"Combing Your Hair With a Hedgehog",
	"Tramp Stamp",
	"Crap Parkour",
	"Badly-Trained Dentist",
	"The Heimlich Maneuver",
	"A Bizarre Gardening Accident",
	"Bum Bongos",
	"Aztec Sacrifice",
	"Awkward Family Photo",
	"Making an Onion Cry",
	"Crushing a Child's Sandcastle",
	"Giraffe Limbo Contest",
	"Shouting at Old People",
	"Walking Into a Mirror",
	"Touchy-Feely Geography Teacher",
	"Lactose Intolerance",
	"LARPing",
	"Velociraptor Jesus",
	"Police Line-Up",
	"Awkward Hug",
	"Running Away From Your Problems",
	"Staring Contest",
	"Eye-Wateringly Strong Chili",
	"Sausage Fingers",
	"Beer Goggles",
	"Trust Exercises",
	"Frisbee Decapitation",
	"Free Willy",
	"Butt Chin",
	"Spontaneous Human Combustion",
	"Sharknado",
	"Moobs",
	"Glued to the Screen",
	"Sexting",
	"Burger Nips",
	"Edible Panties",
	"Babe Magnet",
	"Naked on a Escalator",
	"Banana Hammock",
	"Cow Tipping",
	"Big Girl's Blouse",
	"Cat Got Your Tongue",
	"Talking Shit",
	"Costing an Arm and a Leg",
	"Fear of Toilets",
	"Lost in a Ball Pit",
	"Self-Portrait (of Yourself)",
	"Choking on Doughnuts",
	"Face-Plant",
	"Naked Status of Yourself",
	"Crying Over Spilt Milk",
	"Mail Order Bride",
	"Netflix and Chill",
	"Making an Arse Out of Yourself",
	"Mobility Scooter Hit and Run",
	"Terrified by Butter",
	"Shotgun Wedding",
	"The Fork Museum",
	"Foam Party",
	"Biting Off More Than You Can Chew",
	"Polishing a Turd",
	"Up Shit Creek Without a Paddle",
	"Cereal Killer",
	"Extreme Breastfeeding",
	"Cleaning Out Your Pipes",
	"Popcorn Surprise",
	"Skeleton in Your Closet",
	"At It Like Rabbits",
	"Christmas Dildo",
	"Potty Mouth",
	"Really Ugly Baby",
	"Karate Chopping a Frog",
	"Pet Rock",
	"Unicorn Rainbow Fart",
	"Wispy Beard",
	"Stud Muffin",
	"Seeing a Man About a Horse",
	"Anal Bleaching",
	"Kicking Ducks",
	"Side Boob",
	"Rubbing Someone Up the Wrong Way",
	"Duck Face",
	"Personal Space Invasion",
	"Questionable Parenting",
	"An Unfortunate Birthmark",
	"Extreme Chafing",
	"Erotic Oven Mitts",
	"Beating Around The Bush",
	"Stealing the Covers",
	"Flesh Light",
	"Cheese Nightmare",
	"Reach-Around",
	"A Very Disappointing Christmas",
	"Drinking Problems",
	"Heavy Breathing",
	"Blaze of Glory",
	"Gastric Band",
	"Wheelbarrow Race",
	"Sore Loser",
	"Bronies",
	"Freezing Your Own Head",
	"Dogs Dressed as Humans",
	"Camel Toe",
	"Packing a Sausage",
	"Living in a Skip",
	"Spooning a Spoon",
	"Racist Grandma",
	"Wet Handshake",
	"Tinder Creep",
	"The Ugly Friend",
	"Fighting Fire With Fire",
	"Pathetic Snowman",
	"Bad Babysitter",
	"Holiday in Hell",
}
